version: '3.9'

services:
     
  web:
    build: .
    container_name: fastapi-cicd-container
    command: uvicorn main:app --host 0.0.0.0 --port 8005 --reload
    volumes:
      - .:/app
    ports:
      - "8005:8005"
    


